% !TeX root = ../kappa.Rnw  

% ---------------------------------------------------------
% Project: PhD KAPPA
% File: conclusions.tex
% Author: Alessio Crippa
% based on the template written by Andrea Discacciati
%
% Purpose: Conclusions
% ---------------------------------------------------------

\chapter{Conclusions}

Write summary of conclusions.

More specifically we conclude the following:

\begin{itemize}

\item <>

\item <>

\item <>

\item <> 

\end{itemize}